name: Debug Deploy Process

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Check local build files
        run: |
          echo "Checking build files..."
          ls -la target/
          echo "Current directory:"
          pwd

      - name: Debug - Check Server Before Copy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 234
          script: |
            echo "Current directory on server:"
            pwd
            echo "Checking target directory:"
            ls -la /home/ute/prse/be/
            echo "Disk space:"
            df -h
            echo "Memory usage:"
            free -h

      - name: Deploy JAR file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 234
          source: "target/prse_be.jar"
          target: "/home/ute/prse/be/"
          debug: true
          timeout: "60s"
          strip_components: 1

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 234
          command_timeout: "20m"
          script: |
            cd /home/ute/prse/be/
            ./start.sh restart

      - name: Copy JAR to versions directory
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 234
          source: "target/prse_be.jar"
          target: "/home/ute/prse/be/versions/prse_be_${GITHUB_SHA}.jar"
